from __future__ import annotations

from collections import Counter
from pathlib import Path
from typing import Any

from .io import load_data, write_text


ROADMAP_PATH = Path("docs/ROADMAP.md")
ROADMAP_CHECK_SCHEMA = "agentspec.roadmap_check.v0"


def build_roadmap(root: Path) -> str:
    root = root.resolve()
    handoff = _dict_or_empty(load_data(root / "agent" / "handoff.yml", {}))
    ledger = _dict_or_empty(load_data(root / "agent" / "task-ledger.yml", {}))
    requirements = _list_or_empty(load_data(root / "docs" / "traceability" / "requirements.yml", []))
    tasks = ledger.get("tasks") if isinstance(ledger.get("tasks"), dict) else {}
    task_items = sorted(tasks.items()) if isinstance(tasks, dict) else []

    lines = [
        "# AgentSpec Roadmap",
        "",
        "_Generated by `aspec roadmap`. Do not edit by hand._",
        "",
        "Generated from: `agent/handoff.yml`, `agent/task-ledger.yml`, `docs/traceability/requirements.yml`",
        "",
        "## Current Handoff",
        "",
    ]
    lines.extend(_handoff_lines(handoff))
    lines.extend(["", "## Task Ledger", "", "| Task | Status | Run | Verification | Review | Updated |", "|---|---|---|---|---|---|"])
    if task_items:
        for context_pack, entry in task_items:
            if not isinstance(entry, dict):
                continue
            lines.append(_task_row(context_pack, entry))
    else:
        lines.append("| - | - | - | - | - | - |")

    lines.extend(["", "## Requirement Traceability", ""])
    status_counts = Counter(str(req.get("status")) for req in requirements if isinstance(req, dict) and req.get("status"))
    priority_counts = Counter(str(req.get("priority")) for req in requirements if isinstance(req, dict) and req.get("priority"))
    lines.append(f"- Requirements: {len(requirements)}")
    lines.append(f"- By status: {_count_text(status_counts)}")
    lines.append(f"- By priority: {_count_text(priority_counts)}")

    recent = [req for req in requirements[-10:] if isinstance(req, dict)]
    lines.extend(["", "## Recent Requirements", "", "| Requirement | Priority | Status | Title |", "|---|---|---|---|"])
    if recent:
        for req in recent:
            lines.append(
                "| "
                f"`{req.get('id', '-')}` | "
                f"{req.get('priority', '-')} | "
                f"{req.get('status', '-')} | "
                f"{_escape(str(req.get('title', '-')))} |"
            )
    else:
        lines.append("| - | - | - | - |")

    return "\n".join(lines).rstrip() + "\n"


def write_roadmap(root: Path) -> Path:
    path = root.resolve() / ROADMAP_PATH
    write_text(path, build_roadmap(root))
    return path


def check_roadmap(root: Path) -> dict[str, Any]:
    root = root.resolve()
    path = root / ROADMAP_PATH
    expected = build_roadmap(root)
    actual = path.read_text(encoding="utf-8") if path.exists() else None
    current = actual == expected
    return {
        "schema": ROADMAP_CHECK_SCHEMA,
        "path": str(ROADMAP_PATH),
        "exists": path.exists(),
        "current": current,
        "summary": "docs/ROADMAP.md is current." if current else "docs/ROADMAP.md is missing or stale.",
    }


def _handoff_lines(handoff: dict[str, Any]) -> list[str]:
    if not handoff:
        return ["- Last completed task: none", "- Next action: `aspec status --json`"]
    last = handoff.get("last_completed_task") if isinstance(handoff.get("last_completed_task"), dict) else {}
    next_action = handoff.get("next_action") if isinstance(handoff.get("next_action"), dict) else {}
    return [
        f"- Updated: {handoff.get('updated_at', '-')}",
        f"- Last completed task: `{last.get('id', '-')}` {last.get('context_pack', '-')}",
        f"- Last run: `{last.get('run_id', '-')}`",
        f"- Next action: {next_action.get('kind', 'unknown')} -> `{next_action.get('command', 'aspec status --json')}`",
    ]


def _task_row(context_pack: str, entry: dict[str, Any]) -> str:
    verification = entry.get("verification") if isinstance(entry.get("verification"), dict) else {}
    review = entry.get("code_review") if isinstance(entry.get("code_review"), dict) else {}
    return (
        "| "
        f"`{context_pack}` | "
        f"{entry.get('status', '-')} | "
        f"`{entry.get('run_id', '-')}` | "
        f"{verification.get('status', '-')} | "
        f"{review.get('id', '-') if review else '-'} | "
        f"{entry.get('updated_at', '-')} |"
    )


def _count_text(counts: Counter[str]) -> str:
    if not counts:
        return "-"
    return ", ".join(f"{key}={counts[key]}" for key in sorted(counts))


def _list_or_empty(value: Any) -> list[dict[str, Any]]:
    return [record for record in value if isinstance(record, dict)] if isinstance(value, list) else []


def _dict_or_empty(value: Any) -> dict[str, Any]:
    return value if isinstance(value, dict) else {}


def _escape(value: str) -> str:
    return value.replace("|", "\\|")
