from __future__ import annotations

from collections import Counter
from pathlib import Path
from typing import Any

from .config import load_project_config, merged_runtime_config
from .io import load_data, write_text


ROADMAP_PATH = Path("docs/ROADMAP.md")
ROADMAP_CHECK_SCHEMA = "agentspec.roadmap_check.v0"
ROADMAP_MODE_FULL_FILE = "full-file"
ROADMAP_MODE_GENERATED_BLOCK = "generated-block"
ROADMAP_MODES = {ROADMAP_MODE_FULL_FILE, ROADMAP_MODE_GENERATED_BLOCK}
ROADMAP_BLOCK_BEGIN = "<!-- AGENTSPEC:ROADMAP:BEGIN -->"
ROADMAP_BLOCK_END = "<!-- AGENTSPEC:ROADMAP:END -->"


def build_roadmap(root: Path) -> str:
    root = root.resolve()
    handoff = _dict_or_empty(load_data(root / "agent" / "handoff.yml", {}))
    ledger = _dict_or_empty(load_data(root / "agent" / "task-ledger.yml", {}))
    requirements = _list_or_empty(load_data(root / "docs" / "traceability" / "requirements.yml", []))
    tasks = ledger.get("tasks") if isinstance(ledger.get("tasks"), dict) else {}
    task_items = sorted(tasks.items()) if isinstance(tasks, dict) else []

    lines = [
        "# AgentSpec Roadmap",
        "",
        "_Generated by `aspec roadmap`. Do not edit by hand._",
        "",
        "Generated from: `agent/handoff.yml`, `agent/task-ledger.yml`, `docs/traceability/requirements.yml`",
        "",
        "## Current Handoff",
        "",
    ]
    lines.extend(_handoff_lines(handoff))
    lines.extend(["", "## Task Ledger", "", "| Task | Status | Run | Verification | Review | Updated |", "|---|---|---|---|---|---|"])
    if task_items:
        for context_pack, entry in task_items:
            if not isinstance(entry, dict):
                continue
            lines.append(_task_row(context_pack, entry))
    else:
        lines.append("| - | - | - | - | - | - |")

    lines.extend(["", "## Requirement Traceability", ""])
    status_counts = Counter(str(req.get("status")) for req in requirements if isinstance(req, dict) and req.get("status"))
    priority_counts = Counter(str(req.get("priority")) for req in requirements if isinstance(req, dict) and req.get("priority"))
    lines.append(f"- Requirements: {len(requirements)}")
    lines.append(f"- By status: {_count_text(status_counts)}")
    lines.append(f"- By priority: {_count_text(priority_counts)}")

    recent = [req for req in requirements[-10:] if isinstance(req, dict)]
    lines.extend(["", "## Recent Requirements", "", "| Requirement | Priority | Status | Title |", "|---|---|---|---|"])
    if recent:
        for req in recent:
            lines.append(
                "| "
                f"`{req.get('id', '-')}` | "
                f"{req.get('priority', '-')} | "
                f"{req.get('status', '-')} | "
                f"{_escape(str(req.get('title', '-')))} |"
            )
    else:
        lines.append("| - | - | - | - |")

    return "\n".join(lines).rstrip() + "\n"


def write_roadmap(root: Path) -> Path:
    root = root.resolve()
    path = root / ROADMAP_PATH
    mode = _roadmap_mode(root)
    if mode == ROADMAP_MODE_FULL_FILE:
        write_text(path, build_roadmap(root))
    else:
        write_text(path, _write_generated_block_content(root, path))
    return path


def check_roadmap(root: Path) -> dict[str, Any]:
    root = root.resolve()
    path = root / ROADMAP_PATH
    mode = _roadmap_mode(root)
    expected = build_roadmap(root) if mode == ROADMAP_MODE_FULL_FILE else _build_roadmap_block(root)
    actual = path.read_text(encoding="utf-8") if path.exists() else None
    if mode == ROADMAP_MODE_GENERATED_BLOCK and actual is not None:
        block = _extract_roadmap_block(actual)
        if block is None:
            current = False
            summary = "docs/ROADMAP.md is missing the AgentSpec managed block."
        else:
            current = block == expected
            summary = "docs/ROADMAP.md is current." if current else "docs/ROADMAP.md managed block is stale."
    else:
        current = actual == expected
        summary = "docs/ROADMAP.md is current." if current else "docs/ROADMAP.md is missing or stale."
    return {
        "schema": ROADMAP_CHECK_SCHEMA,
        "path": str(ROADMAP_PATH),
        "mode": mode,
        "exists": path.exists(),
        "current": current,
        "summary": summary,
    }


def _roadmap_mode(root: Path) -> str:
    config = merged_runtime_config(load_project_config(root))
    roadmap = config.get("roadmap") if isinstance(config.get("roadmap"), dict) else {}
    mode = str(roadmap.get("mode", ROADMAP_MODE_FULL_FILE))
    if mode not in ROADMAP_MODES:
        raise ValueError(f"Unsupported roadmap mode: {mode}")
    return mode


def _build_roadmap_block(root: Path) -> str:
    return f"{ROADMAP_BLOCK_BEGIN}\n{build_roadmap(root).rstrip()}\n{ROADMAP_BLOCK_END}\n"


def _write_generated_block_content(root: Path, path: Path) -> str:
    block = _build_roadmap_block(root)
    if not path.exists():
        return block
    existing = path.read_text(encoding="utf-8")
    bounds = _roadmap_block_bounds(existing)
    if bounds is None:
        return _append_roadmap_block(existing, block)
    start, end = bounds
    return existing[:start] + block + existing[end:]


def _append_roadmap_block(existing: str, block: str) -> str:
    if not existing:
        return block
    separator = "" if existing.endswith("\n") else "\n"
    return f"{existing}{separator}{block}"


def _extract_roadmap_block(text: str) -> str | None:
    bounds = _roadmap_block_bounds(text)
    if bounds is None:
        return None
    start, end = bounds
    return text[start:end]


def _roadmap_block_bounds(text: str) -> tuple[int, int] | None:
    start = text.find(ROADMAP_BLOCK_BEGIN)
    if start < 0:
        return None
    end_marker_start = text.find(ROADMAP_BLOCK_END, start + len(ROADMAP_BLOCK_BEGIN))
    if end_marker_start < 0:
        return None
    end = end_marker_start + len(ROADMAP_BLOCK_END)
    if end < len(text) and text[end : end + 1] == "\n":
        end += 1
    return start, end


def _handoff_lines(handoff: dict[str, Any]) -> list[str]:
    if not handoff:
        return ["- Last completed task: none", "- Next action: `aspec status --json`"]
    last = handoff.get("last_completed_task") if isinstance(handoff.get("last_completed_task"), dict) else {}
    next_action = handoff.get("next_action") if isinstance(handoff.get("next_action"), dict) else {}
    return [
        f"- Updated: {handoff.get('updated_at', '-')}",
        f"- Last completed task: `{last.get('id', '-')}` {last.get('context_pack', '-')}",
        f"- Last run: `{last.get('run_id', '-')}`",
        f"- Next action: {next_action.get('kind', 'unknown')} -> `{next_action.get('command', 'aspec status --json')}`",
    ]


def _task_row(context_pack: str, entry: dict[str, Any]) -> str:
    verification = entry.get("verification") if isinstance(entry.get("verification"), dict) else {}
    review = entry.get("code_review") if isinstance(entry.get("code_review"), dict) else {}
    return (
        "| "
        f"`{context_pack}` | "
        f"{entry.get('status', '-')} | "
        f"`{entry.get('run_id', '-')}` | "
        f"{verification.get('status', '-')} | "
        f"{review.get('id', '-') if review else '-'} | "
        f"{entry.get('updated_at', '-')} |"
    )


def _count_text(counts: Counter[str]) -> str:
    if not counts:
        return "-"
    return ", ".join(f"{key}={counts[key]}" for key in sorted(counts))


def _list_or_empty(value: Any) -> list[dict[str, Any]]:
    return [record for record in value if isinstance(record, dict)] if isinstance(value, list) else []


def _dict_or_empty(value: Any) -> dict[str, Any]:
    return value if isinstance(value, dict) else {}


def _escape(value: str) -> str:
    return value.replace("|", "\\|")
