"""Roadmap generation from AgentSpec handoff, evidence, and requirements."""

from __future__ import annotations

from collections import Counter
from pathlib import Path
from typing import Any

from .config import load_project_config, merged_runtime_config
from .evidence import load_public_release_tasks, public_release_evidence_path
from .io import load_data, write_text


ROADMAP_PATH = Path("docs/ROADMAP.md")
ROADMAP_CHECK_SCHEMA = "agentspec.roadmap_check.v0"
ROADMAP_MODE_FULL_FILE = "full-file"
ROADMAP_MODE_GENERATED_BLOCK = "generated-block"
ROADMAP_MODES = {ROADMAP_MODE_FULL_FILE, ROADMAP_MODE_GENERATED_BLOCK}
ROADMAP_BLOCK_BEGIN = "<!-- AGENTSPEC:ROADMAP:BEGIN -->"
ROADMAP_BLOCK_END = "<!-- AGENTSPEC:ROADMAP:END -->"


def build_roadmap(root: Path) -> str:
    """Build the deterministic AgentSpec roadmap Markdown projection."""

    root = root.resolve()
    handoff = _dict_or_empty(load_data(root / "agent" / "handoff.yml", {}))
    ledger = _dict_or_empty(load_data(root / "agent" / "task-ledger.yml", {}))
    public_tasks = load_public_release_tasks(root)
    requirements = _list_or_empty(load_data(root / "docs" / "traceability" / "requirements.yml", []))
    tasks = ledger.get("tasks") if isinstance(ledger.get("tasks"), dict) else {}
    private_tasks: dict[str, Any] = tasks if isinstance(tasks, dict) else {}
    merged_tasks = _merge_task_evidence(public_tasks, private_tasks)
    task_items = sorted(merged_tasks.items())
    generated_from = [
        "`agent/handoff.yml`",
        "`agent/task-ledger.yml`",
        "`docs/traceability/requirements.yml`",
    ]
    if public_tasks:
        generated_from.append(f"`{public_release_evidence_path()}`")

    lines = [
        "# AgentSpec Roadmap",
        "",
        "_Generated by `aspec roadmap`. Do not edit by hand._",
        "",
        f"Generated from: {', '.join(generated_from)}",
        "",
        "## Current Handoff",
        "",
    ]
    lines.extend(_handoff_lines(handoff))
    lines.extend(["", "## Task Ledger", "", "| Task | Status | Run | Verification | Review | Updated |", "|---|---|---|---|---|---|"])
    if task_items:
        for context_pack, entry in task_items:
            if not isinstance(entry, dict):
                continue
            lines.append(_task_row(context_pack, entry))
    else:
        lines.append("| - | - | - | - | - | - |")

    lines.extend(["", "## Requirement Traceability", ""])
    status_counts = Counter(str(req.get("status")) for req in requirements if isinstance(req, dict) and req.get("status"))
    priority_counts = Counter(str(req.get("priority")) for req in requirements if isinstance(req, dict) and req.get("priority"))
    lines.append(f"- Requirements: {len(requirements)}")
    lines.append(f"- By status: {_count_text(status_counts)}")
    lines.append(f"- By priority: {_count_text(priority_counts)}")

    recent = [req for req in requirements[-10:] if isinstance(req, dict)]
    lines.extend(["", "## Recent Requirements", "", "| Requirement | Priority | Status | Title |", "|---|---|---|---|"])
    if recent:
        for req in recent:
            lines.append(
                "| "
                f"`{req.get('id', '-')}` | "
                f"{req.get('priority', '-')} | "
                f"{req.get('status', '-')} | "
                f"{_escape(str(req.get('title', '-')))} |"
            )
    else:
        lines.append("| - | - | - | - |")

    return "\n".join(lines).rstrip() + "\n"


def write_roadmap(root: Path) -> Path:
    """Write the roadmap according to the configured roadmap mode."""

    root = root.resolve()
    path = root / ROADMAP_PATH
    mode = _roadmap_mode(root)
    if mode == ROADMAP_MODE_FULL_FILE:
        write_text(path, build_roadmap(root))
    else:
        write_text(path, _write_generated_block_content(root, path))
    return path


def check_roadmap(root: Path) -> dict[str, Any]:
    """Check whether the roadmap file matches the current projection."""

    root = root.resolve()
    path = root / ROADMAP_PATH
    mode = _roadmap_mode(root)
    expected = build_roadmap(root) if mode == ROADMAP_MODE_FULL_FILE else _build_roadmap_block(root)
    actual = path.read_text(encoding="utf-8") if path.exists() else None
    if mode == ROADMAP_MODE_GENERATED_BLOCK and actual is not None:
        block = _extract_roadmap_block(actual)
        if block is None:
            current = False
            summary = "docs/ROADMAP.md is missing the AgentSpec managed block."
        else:
            current = block == expected
            summary = "docs/ROADMAP.md is current." if current else "docs/ROADMAP.md managed block is stale."
    else:
        current = actual == expected
        summary = "docs/ROADMAP.md is current." if current else "docs/ROADMAP.md is missing or stale."
    return {
        "schema": ROADMAP_CHECK_SCHEMA,
        "path": str(ROADMAP_PATH),
        "mode": mode,
        "exists": path.exists(),
        "current": current,
        "summary": summary,
    }


def _roadmap_mode(root: Path) -> str:
    config = merged_runtime_config(load_project_config(root))
    raw_roadmap = config.get("roadmap")
    roadmap: dict[str, Any] = raw_roadmap if isinstance(raw_roadmap, dict) else {}
    mode = str(roadmap.get("mode", ROADMAP_MODE_FULL_FILE))
    if mode not in ROADMAP_MODES:
        raise ValueError(f"Unsupported roadmap mode: {mode}")
    return mode


def _build_roadmap_block(root: Path) -> str:
    return f"{ROADMAP_BLOCK_BEGIN}\n{build_roadmap(root).rstrip()}\n{ROADMAP_BLOCK_END}\n"


def _write_generated_block_content(root: Path, path: Path) -> str:
    block = _build_roadmap_block(root)
    if not path.exists():
        return block
    existing = path.read_text(encoding="utf-8")
    bounds = _roadmap_block_bounds(existing)
    if bounds is None:
        return _append_roadmap_block(existing, block)
    start, end = bounds
    return existing[:start] + block + existing[end:]


def _append_roadmap_block(existing: str, block: str) -> str:
    if not existing:
        return block
    separator = "" if existing.endswith("\n") else "\n"
    return f"{existing}{separator}{block}"


def _extract_roadmap_block(text: str) -> str | None:
    bounds = _roadmap_block_bounds(text)
    if bounds is None:
        return None
    start, end = bounds
    return text[start:end]


def _roadmap_block_bounds(text: str) -> tuple[int, int] | None:
    start = text.find(ROADMAP_BLOCK_BEGIN)
    if start < 0:
        return None
    end_marker_start = text.find(ROADMAP_BLOCK_END, start + len(ROADMAP_BLOCK_BEGIN))
    if end_marker_start < 0:
        return None
    end = end_marker_start + len(ROADMAP_BLOCK_END)
    if end < len(text) and text[end : end + 1] == "\n":
        end += 1
    return start, end


def _handoff_lines(handoff: dict[str, Any]) -> list[str]:
    if not handoff:
        return ["- Last completed task: none", "- Next action: `aspec status --json`"]
    raw_last = handoff.get("last_completed_task")
    raw_next_action = handoff.get("next_action")
    last: dict[str, Any] = raw_last if isinstance(raw_last, dict) else {}
    next_action: dict[str, Any] = raw_next_action if isinstance(raw_next_action, dict) else {}
    return [
        f"- Updated: {handoff.get('updated_at', '-')}",
        f"- Last completed task: `{last.get('id', '-')}` {last.get('context_pack', '-')}",
        f"- Last run: `{last.get('run_id', '-')}`",
        f"- Next action: {next_action.get('kind', 'unknown')} -> `{next_action.get('command', 'aspec status --json')}`",
    ]


def _task_row(context_pack: str, entry: dict[str, Any]) -> str:
    raw_verification = entry.get("verification")
    raw_review = entry.get("code_review")
    verification: dict[str, Any] = raw_verification if isinstance(raw_verification, dict) else {}
    review: dict[str, Any] = raw_review if isinstance(raw_review, dict) else {}
    return (
        "| "
        f"`{context_pack}` | "
        f"{entry.get('status', '-')} | "
        f"`{entry.get('run_id', '-')}` | "
        f"{verification.get('status', '-')} | "
        f"{review.get('id', '-') if review else '-'} | "
        f"{entry.get('updated_at', '-')} |"
    )


def _merge_task_evidence(
    public_tasks: dict[str, dict[str, Any]],
    private_tasks: dict[str, Any],
) -> dict[str, dict[str, Any]]:
    merged = {context_pack: dict(entry) for context_pack, entry in public_tasks.items()}
    for context_pack, private_entry in private_tasks.items():
        if not isinstance(context_pack, str) or not isinstance(private_entry, dict):
            continue
        public_entry = public_tasks.get(context_pack)
        if public_entry is None:
            merged[context_pack] = private_entry
            continue
        combined = {**public_entry, **private_entry}
        if _public_review_is_newer(public_entry, private_entry):
            for key in ("code_review", "reviews", "review_updated_at"):
                if key in public_entry:
                    combined[key] = public_entry[key]
        merged[context_pack] = combined
    return merged


def _public_review_is_newer(
    public_entry: dict[str, Any],
    private_entry: dict[str, Any],
) -> bool:
    public_review = public_entry.get("code_review")
    if not isinstance(public_review, dict):
        return False
    public_updated = str(public_entry.get("review_updated_at") or public_entry.get("updated_at") or "")
    private_updated = str(private_entry.get("review_updated_at") or private_entry.get("updated_at") or "")
    return bool(public_updated) and public_updated > private_updated


def _count_text(counts: Counter[str]) -> str:
    if not counts:
        return "-"
    return ", ".join(f"{key}={counts[key]}" for key in sorted(counts))


def _list_or_empty(value: Any) -> list[dict[str, Any]]:
    return [record for record in value if isinstance(record, dict)] if isinstance(value, list) else []


def _dict_or_empty(value: Any) -> dict[str, Any]:
    return value if isinstance(value, dict) else {}


def _escape(value: str) -> str:
    return value.replace("|", "\\|")
